hte_index:
    pattern:  /hte/
    defaults: { _controller: HteSiteBundle:Site:index }

hte_about:
    pattern:  /hte/about{trailingSlash}
    defaults: { _controller: HteSiteBundle:Site:about, trailingSlash : "/" }
    requirements: { trailingSlash : "[/]{0,1}" }

hte_product_samples:
    pattern:  /hte/product-samples{trailingSlash}
    defaults: { _controller: HteSiteBundle:Site:productSamples, trailingSlash : "/" }
    requirements: { trailingSlash : "[/]{0,1}" }

hte_capabilities:
    pattern:  /hte/capabilities{trailingSlash}
    defaults: { _controller: HteSiteBundle:Site:capabilities, trailingSlash : "/" }
    requirements: { trailingSlash : "[/]{0,1}" }

hte_contact:
    pattern:  /hte/contact{trailingSlash}
    defaults: { _controller: HteSiteBundle:Site:contact, trailingSlash : "/" }
    requirements: { trailingSlash : "[/]{0,1}" }
